#!/usr/bin/env bash
REPO="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ ! -e ~/.vimrc ]
then
    ln -s $REPO/.vimrc ~/.vimrc
fi

if [ ! -e ~/.gvimrc ]
then
    ln -s $REPO/.gvimrc ~/.gvimrc
fi

# Plugins
if [ ! -e ~/.vim/pack ]
then
    mkdir ~/.vim/pack
fi
if [ ! -e ~/.vim/pack/plugins ]
then
    ln -s $REPO/plugins ~/.vim/pack/plugins
fi

